# Generated by Django 5.1.1 on 2025-03-22 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('displayname', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(default='john_doe', max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default='noemail@domain.com', max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
