# Generated by Django 5.1.1 on 2025-03-22 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
