# Generated by Django 5.1.1 on 2024-10-30 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_username'),
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaults', to='users.profile'),
        ),
    ]
