# Generated by Django 5.1.1 on 2024-10-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0003_remove_vault_content_vaultmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultmedia',
            name='file',
            field=models.FileField(upload_to='vault_media/'),
        ),
    ]
