# Generated by Django 5.1.1 on 2025-04-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0003_alter_vaultmedia_options_alter_vault_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vault',
            old_name='max_media_items',
            new_name='uploads_per_person',
        ),
    ]
