# Generated by Django 5.1.1 on 2024-11-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0004_alter_vaultmedia_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vault',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='vaultmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
