# Generated by Django 5.1.1 on 2025-04-08 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vaults', '0005_vaultmedia_uploader_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultmedia',
            name='uploader_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to='users.profile'),
        ),
    ]
