# Generated by Django 5.1.1 on 2024-11-19 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0005_alter_vault_options_vaultmedia_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaultmedia',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='vault',
            name='guest_num',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='vault',
            name='photos_per_person',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
