# Generated by Django 5.1.1 on 2025-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vaults', '0006_alter_vaultmedia_uploader_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='qr_code_valid_from',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vault',
            index=models.Index(fields=['qr_code_valid_from'], name='vaults_vaul_qr_code_a86aaa_idx'),
        ),
    ]
