# Generated by Django 5.1.1 on 2024-11-19 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0006_alter_vaultmedia_options_vault_guest_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='guest_num',
            field=models.IntegerField(blank=True, default=2, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
