# Generated by Django 5.1.1 on 2024-11-19 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0007_alter_vault_guest_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='photos_per_person',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
