# Generated by Django 5.1.1 on 2025-04-15 17:19

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('users', '0001_initial'),
        ('vaults', '0007_vault_qr_code_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaultmedia',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='vaultmedia',
            name='vaults_vaul_vault_i_24f77a_idx',
        ),
        migrations.AlterField(
            model_name='vaultmedia',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='vaultmedia',
            name='uploader_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to='users.profile'),
        ),
        migrations.AddIndex(
            model_name='vaultmedia',
            index=models.Index(fields=['vault', '-created_at'], name='vaults_vaul_vault_i_72cc77_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultmedia',
            index=models.Index(fields=['created_at'], name='vaults_vaul_created_b2d3ed_idx'),
        ),
    ]
