# Generated by Django 5.1.1 on 2024-12-10 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0008_alter_vault_photos_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='vault_qrcodes/'),
        ),
        migrations.AlterField(
            model_name='vault',
            name='photos_per_person',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
