# Generated by Django 5.1.1 on 2025-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0009_alter_vaultmedia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='qr_code_active_minutes',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
