# Generated by Django 5.1.1 on 2024-12-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0009_vault_qr_code_alter_vault_photos_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='max_media_items',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
