# Generated by Django 5.1.1 on 2025-04-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0010_vault_qr_code_active_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vault',
            name='qr_code_active_minutes',
        ),
        migrations.AddField(
            model_name='vault',
            name='qr_code_active_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
