# Generated by Django 5.1.1 on 2024-12-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0010_vault_max_media_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='max_media_items',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
