# Generated by Django 5.1.1 on 2025-05-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0011_remove_vault_qr_code_active_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='qr_code_active_days',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
