# Generated by Django 5.1.1 on 2024-12-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0012_alter_vault_max_media_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vault',
            name='guest_num',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='photos_per_person',
        ),
    ]
